### ISSUE TITLE
lru remove is not O(1)

### ISSUE THREAD

**Issue by StephenEhmann** [erikdubbelboer/erik-misc-code#1]
I don't think that lur.remove is O(1) since you have this:
lru.remove(key);  // O(1)
shouldn't it be:
lru.remove(i->second.second);

**Comment by StephenEhmann** [comment]
corrected the code in the description: remove -> erase in the proposed change.

**Comment by erikdubbelboer** [comment]
Very good find, thanks.

**Comment by StephenEhmann** [comment]
I also see a few comments labeling things O(lg n) when those should all be
O(1) I think.

**Comment by erikdubbelboer** [comment]
No lookups in `std::map` are O(log n). The 0x version allows you to plug in `std::unordered_map` instead which has O(1) lookups. I wrote about the performance trade-offs here: http://blog.dubbelboer.com/2012/12/04/lru-cache.html

**Comment by StephenEhmann** [comment]
My bad . I had been using unordered map so much i forgot that the original
implementation has map.
